### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by amcdnl** [andrglo/koa-swagger-router#1]
any plans for docs?

**Comment by andrglo** [comment]
Yes, when requested! Do you intend to use?

**Comment by amcdnl** [comment]
would just be helpful to understand what it even is ;)

**Comment by andrglo** [comment]
It enforces documentation by automatically creating a route (/spec) that returns a Swagger specification

Suppose, using koa-router, you'll create a route like:

```
  router
    .get(`/machine/:who`, function*() {
      this.body = {
        message: `Hello ${this.params.who}, this is "The Machine" speaking!`
      };
    });
```

With koa-swagger-router, that internally uses koa-router, an extra route is added to return the specification, so you write:

```
router
  .get(`/machine/:who`, function*() {
    this.body = {
      message: `Hello ${this.params.who}, this is "The Machine" speaking!`
    };
  })
  .params({
    in: 'path',
    name: 'who',
    description: `Who is calling ?`
  });
```

And get an extra route:

```
router.get('/spec', function*() {
  this.body = {
    ...
      "/machine/{who}": {
    "get": {
      "tags": [
        "machine"
      ],
        "summary": "Get Machine",
        "description": "",
        "responses": {
        "200": {
          "description": "Success"
        },
        "400": {
          "description": "Error"
        }
      },
      "security": [
        {
          "internalApiKey": []
        }
      ],
        "parameters": [
        {
          "in": "path",
          "name": "who",
          "description": "Who is calling ?",
          "required": true,
          "type": "string"
        }
      ]
    }
  }
    ...
  };
}))
```

**Comment by amcdnl** [comment]
How is it different from something like: https://github.com/cyner/swagger-koa

Also, it laying on top of a router seems not-ideal, why not just hook it?

**Comment by andrglo** [comment]
Same result but my approach using the router 'merged' with the spec really forces you to do the job and can even check some information like the params. 

This approach only extract the documentation from different sources to build the spec and then serve it.

Yes, hook it would be better. I'll work on it. Also the logger and authorization need to be hooked

**Comment by amcdnl** [comment]
I think I'm gonna roll something like [jsdoc swagger](https://www.npmjs.com/package/swagger-jsdoc) and then serve it [swagger-injector](https://github.com/johnhof/swagger-injector).

I know its not very 'swagger-ish' ( haha ) but its pretty light and does the job.

**Comment by andrglo** [comment]
Good options. This _adaptation of swagger UI_ seems nice, I'll give it a try

**Comment by amcdnl** [comment]
Ya, its pretty slick.  Got it working very easily: http://www.screencast.com/t/HJ42Gavlyx with a hook like this: http://www.screencast.com/t/jfJNKmQlLJ
